"""create forest patrol schema

Revision ID: f0rest000001
Revises: 
Create Date: 2026-09-17 18:33:37.100275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.guid


revision: str = 'f0rest000001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acoustic_events',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=128), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=128), nullable=False),
    sa.Column('record_hash', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=2048), nullable=False),
    sa.Column('signature_status', sa.String(length=16), nullable=False),
    sa.Column('chain_status', sa.String(length=16), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('gateway_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backend_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_acoustic_events_event_id'),
    sa.UniqueConstraint('node_id', 'sequence', name='uq_acoustic_events_node_sequence')
    )
    op.create_index('ix_acoustic_events_checkpoint', 'acoustic_events', ['checkpoint_id'], unique=False)
    op.create_index('ix_acoustic_events_created', 'acoustic_events', ['event_created_at'], unique=False)
    op.create_index('ix_acoustic_events_review', 'acoustic_events', ['review_status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('zone_id', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoint_id', name='uq_checkpoints_checkpoint_id')
    )
    op.create_index('ix_checkpoints_active', 'checkpoints', ['active'], unique=False)
    op.create_index('ix_checkpoints_zone', 'checkpoints', ['zone_id'], unique=False)
    op.create_table('forest_nodes',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('public_key', sa.String(length=1024), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', name='uq_forest_nodes_node_id')
    )
    op.create_index('ix_forest_nodes_checkpoint', 'forest_nodes', ['checkpoint_id'], unique=False)
    op.create_index('ix_forest_nodes_status', 'forest_nodes', ['status'], unique=False)
    op.create_table('gateways',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('gateway_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lora_status', sa.String(length=32), nullable=True),
    sa.Column('wifi_status', sa.String(length=32), nullable=True),
    sa.Column('backend_status', sa.String(length=32), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_forwarded', sa.Integer(), nullable=False),
    sa.Column('records_pending', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_id', name='uq_gateways_gateway_id')
    )
    op.create_index('ix_gateways_status', 'gateways', ['status'], unique=False)
    op.create_table('patrol_events',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=64), nullable=True),
    sa.Column('officer_id', sa.String(length=64), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('rfid_result', sa.String(length=16), nullable=True),
    sa.Column('fingerprint_result', sa.String(length=16), nullable=True),
    sa.Column('event_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gateway_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backend_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_hash', sa.String(length=128), nullable=False),
    sa.Column('record_hash', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=2048), nullable=False),
    sa.Column('signature_status', sa.String(length=16), nullable=False),
    sa.Column('chain_status', sa.String(length=16), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_patrol_events_event_id'),
    sa.UniqueConstraint('node_id', 'sequence', name='uq_patrol_events_node_sequence')
    )
    op.create_index('ix_patrol_events_checkpoint', 'patrol_events', ['checkpoint_id'], unique=False)
    op.create_index('ix_patrol_events_created', 'patrol_events', ['event_created_at'], unique=False)
    op.create_index('ix_patrol_events_officer', 'patrol_events', ['officer_id'], unique=False)
    op.create_index('ix_patrol_events_sync', 'patrol_events', ['sync_status'], unique=False)
    op.create_table('patrol_officers',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('officer_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('badge_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officer_id', name='uq_patrol_officers_officer_id')
    )
    op.create_index('ix_patrol_officers_status', 'patrol_officers', ['status'], unique=False)
    op.create_table('sync_records',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('sync_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('gateway_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forwarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'gateway_id', name='uq_sync_records_event_gateway')
    )
    op.create_index('ix_sync_records_node', 'sync_records', ['node_id'], unique=False)
    op.create_index('ix_sync_records_status', 'sync_records', ['sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_records_status', table_name='sync_records')
    op.drop_index('ix_sync_records_node', table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_index('ix_patrol_officers_status', table_name='patrol_officers')
    op.drop_table('patrol_officers')
    op.drop_index('ix_patrol_events_sync', table_name='patrol_events')
    op.drop_index('ix_patrol_events_officer', table_name='patrol_events')
    op.drop_index('ix_patrol_events_created', table_name='patrol_events')
    op.drop_index('ix_patrol_events_checkpoint', table_name='patrol_events')
    op.drop_table('patrol_events')
    op.drop_index('ix_gateways_status', table_name='gateways')
    op.drop_table('gateways')
    op.drop_index('ix_forest_nodes_status', table_name='forest_nodes')
    op.drop_index('ix_forest_nodes_checkpoint', table_name='forest_nodes')
    op.drop_table('forest_nodes')
    op.drop_index('ix_checkpoints_zone', table_name='checkpoints')
    op.drop_index('ix_checkpoints_active', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_acoustic_events_review', table_name='acoustic_events')
    op.drop_index('ix_acoustic_events_created', table_name='acoustic_events')
    op.drop_index('ix_acoustic_events_checkpoint', table_name='acoustic_events')
    op.drop_table('acoustic_events')
    # ### end Alembic commands ###

