#!/usr/bin/env python3
"""Embed ml/models/final/forest_acoustic_int8.tflite as lib/Acoustic/src/AcousticModelData.h.

Run:  python3 tools/embed_model.py
"""
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "ml" / "models" / "final" / "forest_acoustic_int8.tflite"
OUT = Path(__file__).resolve().parents[1] / "lib" / "Acoustic" / "src" / "AcousticModelData.h"

data = SRC.read_bytes()
rows = []
for i in range(0, len(data), 16):
    rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
OUT.write_text("\n".join([
    "// GENERATED by tools/embed_model.py - do not edit.",
    f"// Source: ml/models/final/forest_acoustic_int8.tflite ({len(data)} bytes)",
    f"// sha256: {hashlib.sha256(data).hexdigest()}",
    "#pragma once",
    "",
    "namespace forest::acoustic {",
    "// const => placed in flash, not RAM.",
    f"alignas(16) inline const unsigned char kModelData[{len(data)}] = {{",
    *rows,
    "};",
    f"inline constexpr unsigned int kModelDataLen = {len(data)};",
    "}  // namespace forest::acoustic",
    "",
]))
print(f"wrote {OUT} ({len(data)} model bytes)")
