#!/usr/bin/env python3
"""Generate lib/Acoustic/src/AcousticTables.h from the ml/ pipeline definitions.

Reads only (never modifies) ml/. Reproduces exactly what
ml/preprocessing/feature_extraction.py + ml/models/convert_tflite.py compute:
  librosa.feature.melspectrogram(n_fft=512, hop_length=160, n_mels=40, fmin=0,
  fmax=8000, power=2)  ->  power_to_db(ref=max)  ->  (dB - mean) / std  ->  int8.

Run:  python3 tools/gen_acoustic_tables.py
"""
import json
from pathlib import Path

import librosa
import numpy as np
import scipy.signal
import yaml

ROOT = Path(__file__).resolve().parents[2]
ML = ROOT / "ml"
OUT = Path(__file__).resolve().parents[1] / "lib" / "Acoustic" / "src" / "AcousticTables.h"

cfg = yaml.safe_load(open(ML / "configs" / "preprocessing.yaml"))
mel_cfg = cfg["features"]["mel_spectrogram"] if "features" in cfg else cfg["mel_spectrogram"]
meta = json.load(open(ML / "models" / "final" / "final_metadata.json"))

SR = cfg["audio"]["target_sample_rate"] if "audio" in cfg and "target_sample_rate" in cfg["audio"] else 16000
N_FFT = int(mel_cfg["n_fft"])
HOP = int(mel_cfg["hop_length"])
N_MELS = int(mel_cfg["n_mels"])
FMIN = float(mel_cfg["fmin"])
FMAX = float(mel_cfg["fmax"])
POWER = float(mel_cfg["power"])
assert (SR, N_FFT, HOP, N_MELS, FMIN, FMAX, POWER) == (16000, 512, 160, 40, 0.0, 8000.0, 2.0), \
    "ml/ configuration changed - the firmware port must be revisited"

# librosa defaults used implicitly by the training pipeline (librosa 0.11.0).
window = scipy.signal.get_window("hann", N_FFT, fftbins=True).astype(np.float32)
fb = librosa.filters.mel(sr=SR, n_fft=N_FFT, n_mels=N_MELS, fmin=FMIN, fmax=FMAX).astype(np.float32)  # (40, 257)

mean = float(meta["feature_mean"])
std = float(meta["feature_std"])

import tensorflow as tf  # noqa: E402  (only to read the real quantization params)
interp = tf.lite.Interpreter(model_path=str(ML / "models" / "final" / "forest_acoustic_int8.tflite"))
interp.allocate_tensors()
in_d = interp.get_input_details()[0]
out_d = interp.get_output_details()[0]
in_scale, in_zp = in_d["quantization"]
out_scale, out_zp = out_d["quantization"]
assert list(in_d["shape"]) == [1, 40, 101, 1] and in_d["dtype"] == np.int8
assert list(out_d["shape"]) == [1, 3] and out_d["dtype"] == np.int8

def flt(a):
    return ", ".join(f"{float(x):.9e}f" for x in a)

starts, lens, weights = [], [], []
for m in range(N_MELS):
    nz = np.nonzero(fb[m])[0]
    s, e = int(nz[0]), int(nz[-1]) + 1
    assert np.all(fb[m, s:e] >= 0) and np.all(fb[m, :s] == 0) and np.all(fb[m, e:] == 0)
    starts.append(s); lens.append(e - s); weights.extend(fb[m, s:e].tolist())
offsets = np.concatenate([[0], np.cumsum(lens)]).astype(int)

lines = [
    "// GENERATED by tools/gen_acoustic_tables.py - do not edit.",
    "// Source of truth: ml/configs/preprocessing.yaml, ml/models/final/*.",
    "#pragma once",
    "#include <cstdint>",
    "",
    "namespace forest::acoustic::tables {",
    f"constexpr int kSampleRate = {SR};",
    f"constexpr int kNFft = {N_FFT};",
    f"constexpr int kHop = {HOP};",
    f"constexpr int kNMels = {N_MELS};",
    f"constexpr int kNBins = {N_FFT // 2 + 1};",
    f"constexpr int kWindowSamples = {SR};  // 1.0 s",
    f"constexpr int kNFrames = {1 + SR // HOP};  // librosa center=True",
    f"constexpr float kFeatureMean = {mean:.9e}f;",
    f"constexpr float kFeatureStd = {std:.9e}f;",
    f"constexpr float kInputScale = {float(in_scale):.9e}f;",
    f"constexpr int kInputZeroPoint = {int(in_zp)};",
    f"constexpr float kOutputScale = {float(out_scale):.9e}f;",
    f"constexpr int kOutputZeroPoint = {int(out_zp)};",
    f"constexpr int kMelNonZero = {len(weights)};",
    "// Class order of the trained model (ml/models/final/labels.txt).",
    'constexpr const char* kClassNames[3] = {"background", "chainsaw", "gunshot"};',
    "",
    "// Hann window, periodic (scipy get_window('hann', 512, fftbins=True)), as librosa uses.",
    f"inline constexpr float kHann[{N_FFT}] = {{{flt(window)}}};",
    "",
    "// Slaney mel filterbank (librosa.filters.mel, norm='slaney'), stored sparsely:",
    "// filter m uses FFT bins [kMelStart[m], kMelStart[m]+kMelLen[m]) with weights",
    "// kMelWeights[kMelOffset[m] ...].",
    f"inline constexpr uint16_t kMelStart[{N_MELS}] = {{{', '.join(map(str, starts))}}};",
    f"inline constexpr uint16_t kMelLen[{N_MELS}] = {{{', '.join(map(str, lens))}}};",
    f"inline constexpr uint16_t kMelOffset[{N_MELS + 1}] = {{{', '.join(map(str, offsets))}}};",
    f"inline constexpr float kMelWeights[{len(weights)}] = {{{flt(weights)}}};",
    "}  // namespace forest::acoustic::tables",
    "",
]
OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({OUT.stat().st_size} bytes); mel non-zero weights={len(weights)}")
print(f"input q: scale={in_scale} zp={in_zp}; output q: scale={out_scale} zp={out_zp}; mean={mean} std={std}")
